name: stream_mate
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  lottie: ^3.1.0
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0
  timer_button: ^2.1.1
  pinput: ^4.0.0
  flutter_riverpod: ^2.5.1
  cloud_firestore: ^4.15.10
  image_picker: ^1.0.7
  firebase_storage: ^11.6.11
  firebase_app_check: ^0.2.1+19
  video_player: ^2.8.5
  flutter_speed_dial: ^7.0.0
  cached_network_image: ^3.3.1
  geolocator: ^11.0.0
  fluttertoast: ^8.2.4
  geocoding: ^3.0.0
  uuid: ^4.3.3
  shimmer: ^3.0.0
  intl: ^0.19.0
  video_thumbnail: ^0.5.3
  flutter_cache_manager: ^3.3.1
  loading_animation_widget: ^1.2.1
  modal_bottom_sheet: ^3.0.0
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0

flutter:
  
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/Images/

flutter_native_splash:
  color: "#000000"
  image: assets/Images/logo.png
  android_12:
    image: assets/Images/logo.png
    color: "#000000"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Images/adaptive_logo.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/Images/adaptive_logo.png"
  adaptive_icon_background: "#000000"
  web:
    generate: true
    image_path: "assets/Images/adaptive_logo.png"
    background_color: "#000000"
    theme_color: "#000000"