// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVtfoSV7ztsLFx-SBU7Rp2UKwK2VDjH0I',
    appId: '1:202035267098:web:1697584f16b66654f373a3',
    messagingSenderId: '202035267098',
    projectId: 'stream-mate',
    authDomain: 'stream-mate.firebaseapp.com',
    storageBucket: 'stream-mate.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXyStXJPP9YXUm18iR7BcIi4z0mFXTCPM',
    appId: '1:202035267098:android:eeb5776aa8f07feff373a3',
    messagingSenderId: '202035267098',
    projectId: 'stream-mate',
    storageBucket: 'stream-mate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1mdyJh72yhp3MKRYhznc5TkGDHimXE-Q',
    appId: '1:202035267098:ios:76b540400d044618f373a3',
    messagingSenderId: '202035267098',
    projectId: 'stream-mate',
    storageBucket: 'stream-mate.appspot.com',
    iosBundleId: 'com.example.streamMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1mdyJh72yhp3MKRYhznc5TkGDHimXE-Q',
    appId: '1:202035267098:ios:36ea14eda2230fecf373a3',
    messagingSenderId: '202035267098',
    projectId: 'stream-mate',
    storageBucket: 'stream-mate.appspot.com',
    iosBundleId: 'com.example.streamMate.RunnerTests',
  );
}
